// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBctLfIRakzbWujJnlgAPh8-5qQHST-EYY',
    appId: '1:176895512440:web:47b38f25ba7897198c028d',
    messagingSenderId: '176895512440',
    projectId: 'aura-mart-4f432',
    authDomain: 'aura-mart-4f432.firebaseapp.com',
    storageBucket: 'aura-mart-4f432.firebasestorage.app',
    measurementId: 'G-SYBBWNVSVY',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCy2J_pcqeGNj0-QXw6sOaMloTAStgCKOM',
    appId: '1:176895512440:android:4ca95799a36e5b998c028d',
    messagingSenderId: '176895512440',
    projectId: 'aura-mart-4f432',
    storageBucket: 'aura-mart-4f432.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyByETWeeeffXeW-wShx5IJ8F1qvYwnAqM8',
    appId: '1:176895512440:ios:2821072351d7ec838c028d',
    messagingSenderId: '176895512440',
    projectId: 'aura-mart-4f432',
    storageBucket: 'aura-mart-4f432.firebasestorage.app',
    iosBundleId: 'com.auramart.auraMart',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyByETWeeeffXeW-wShx5IJ8F1qvYwnAqM8',
    appId: '1:176895512440:ios:2821072351d7ec838c028d',
    messagingSenderId: '176895512440',
    projectId: 'aura-mart-4f432',
    storageBucket: 'aura-mart-4f432.firebasestorage.app',
    iosBundleId: 'com.auramart.auraMart',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBctLfIRakzbWujJnlgAPh8-5qQHST-EYY',
    appId: '1:176895512440:web:d142b66b81355e1f8c028d',
    messagingSenderId: '176895512440',
    projectId: 'aura-mart-4f432',
    authDomain: 'aura-mart-4f432.firebaseapp.com',
    storageBucket: 'aura-mart-4f432.firebasestorage.app',
    measurementId: 'G-WW48RQT73X',
  );
}
